### ISSUE TITLE
numeric values are not indexed as keys

### ISSUE THREAD

**Issue by davidavdav** [nalimilan/Tables.jl#2]
This may be a problem of NamedArrays. 

```
julia> freqtable([0,1])
ERROR: BoundsError()
 in setindex! at /Users/david/.julia/v0.3/NamedArrays/src/index.jl:72
 in freqtable at /Users/david/werk/julia/Tables.jl/src/freqtable.jl:69
```
Problem is the values (0, 1) are the keys the dicts used in NamedArrays.  getindex() works, but setindex!() not.

**Comment by davidavdav** [comment]
Fixed by https://github.com/davidavdav/NamedArrays.jl/commit/fa78640b3d516905f7d6883843648c0f3e0296f9

**Comment by nalimilan** [comment]
Cool, thanks!
